name: Direct Docker Build and Deploy to EC2

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to EC2
      env:
        PRIVATE_KEY: ${{ secrets.AWS_VM_SSH_KEY }}
        HOST: ${{ secrets.AWS_VM_HOST }}
        USER: ${{ secrets.AWS_VM_USERNAME }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} 'mkdir -p ~/app_ohif_tmp'
        scp -i private_key -o StrictHostKeyChecking=no -r ./* ${USER}@${HOST}:~/app_ohif_tmp
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          sudo rm -rf /var/www/html/ohif-viewer/app/*
          sudo mv ~/app_ohif_tmp /var/www/html/ohif-viewer/app
        '

    - name: Build and run Docker container on EC2
      env:
        PRIVATE_KEY: ${{ secrets.AWS_VM_SSH_KEY }}
        HOST: ${{ secrets.AWS_VM_HOST }}
        USER: ${{ secrets.AWS_VM_USERNAME }}
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cd /var/www/html/ohif-viewer/app
          
          if [ ! -f Dockerfile ]; then
            echo "Dockerfile not found in expected location!"
            exit 1
          fi
          
          IMAGE_TAG=$(date +%s)
          docker build -t ohif-viewer-image:$IMAGE_TAG .
          
          if [ $(docker ps -q -f name=ohif-viewer-container) ]; then
            echo "Stopping existing container..."
            docker stop ohif-viewer-container
          fi
          
          if [ $(docker ps -a -q -f name=ohif-viewer-container) ]; then
            echo "Removing existing container and its volumes..."
            docker rm -v ohif-viewer-container
          fi
          
          docker run -d -p 3000:80/tcp \
            -v /var/www/html/ohif-viewer/default.js:/usr/share/nginx/html/app-config.js \
            --name ohif-viewer-container ohif-viewer-image:$IMAGE_TAG
        '

    - name: Cleanup
      run: rm -f private_key
