name: Direct Docker Build and Deploy to EC2

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to EC2
      env:
        PRIVATE_KEY: ${{ secrets.AWS_VM_SSH_KEY }}
        HOST: ${{ secrets.AWS_VM_HOST }}
        USER: ${{ secrets.AWS_VM_USERNAME }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

        # Create app directory if it doesn't exist and ensure permissions
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          sudo mkdir -p /var/www/html/ohif-viewer/app && sudo chown -R ${USER}:${USER} /var/www/html/ohif-viewer/app
        '

        # Copy files to the EC2 instance
        scp -i private_key -o StrictHostKeyChecking=no -r ./* ${USER}@${HOST}:/var/www/html/ohif-viewer/app

    - name: Build and run Docker container on EC2
      env:
        PRIVATE_KEY: ${{ secrets.AWS_VM_SSH_KEY }}
        HOST: ${{ secrets.AWS_VM_HOST }}
        USER: ${{ secrets.AWS_VM_USERNAME }}
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cd /var/www/html/ohif-viewer/app
          sudo docker build -t ohif-viewer-image .

          # Stop and remove any existing container with the same name
          sudo docker stop ohif-viewer-container || true
          sudo docker rm ohif-viewer-container || true

          # Run the new container, mapping necessary volumes and ports
          sudo docker run -d -p 3000:80/tcp -v /var/www/html/ohif-viewer/default.js:/usr/share/nginx/html/app-config.js --name ohif-viewer-container ohif-viewer-image
        '

    - name: Cleanup
      run: rm -f private_key
