name: Direct Docker Build and Deploy to EC2

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to EC2
      env:
        PRIVATE_KEY: ${{ secrets.AWS_VM_SSH_KEY }}
        HOST: ${{ secrets.AWS_VM_HOST }}
        USER: ${{ secrets.AWS_VM_USERNAME }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no -r ./* ${USER}@${HOST}:/var/www/html/ohif-viewer/app

    - name: Build and run Docker container on EC2
      env:
        PRIVATE_KEY: ${{ secrets.AWS_VM_SSH_KEY }}
        HOST: ${{ secrets.AWS_VM_HOST }}
        USER: ${{ secrets.AWS_VM_USERNAME }}
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cd /var/www/html/ohif-viewer/app
          docker build -t ohif-viewer-image .
          docker stop ohif-viewer-container || true
          docker rm ohif-viewer-container || true
          docker run -d -p 3000:80/tcp -v /var/www/html/ohif-viewer/default.js:/usr/share/nginx/html/app-config.js --name ohif-viewer-container ohif-viewer-image
        '

    - name: Cleanup
      run: rm -f private_key
